M48
; DRILL file {KiCad 8.0.3} date 2024-07-15T16:50:19+1000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-15T16:50:19+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0830
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X8.8831Y-4.2143
T2
X9.4343Y-4.2143
T3
X8.7142Y-3.6106
X8.7142Y-3.6106
X9.6039Y-3.6106
M30
